#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    for p in /etc/sted2/sted2.cnf /etc/sted2; do
        if dpkg-statoverride --list "$p" >/dev/null 2>&1; then
            dpkg-statoverride --remove "$p"
        fi
    done
fi

#DEBHELPER#
